(() => {
  const api = async (path, method = "GET", body) => { const response = await fetch(path, { method, headers: { "content-type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({ error: "Respuesta inválida" })); if (!response.ok) throw Error(data.error || `HTTP ${response.status}`); return data; };
  const state = { roles: [], editing: null };
  const $ = (selector) => document.querySelector(selector);
  const form = $("#role-form"), id = $("#id"), label = $("#label"), scope = $("#scope"), notice = $("#notice"), roles = $("#roles"), save = $("#save"), cancel = $("#cancel");
  if (!form) return;
  const pluginLink = document.createElement("a"); pluginLink.href = "/plugin-capabilities.html"; pluginLink.className = "admin-link"; pluginLink.textContent = "Gestionar capacidades de plugins"; form.before(pluginLink);
  const sensitive = document.createElement("label"); sensitive.className = "perm management"; sensitive.innerHTML = '<input type="checkbox" value="sensitive:approve"> Aprobar operaciones irreversibles'; $("#permissions").append(sensitive);
  const selected = () => [...form.querySelectorAll("input[type=checkbox]:checked")].map((input) => input.value);
  const updateScope = () => { const external = scope.value === "external"; form.querySelectorAll(".management").forEach((item) => { item.hidden = external; if (external) item.querySelector("input").checked = false; }); };
  const reset = () => { state.editing = null; form.reset(); id.disabled = false; $("#form-title").textContent = "Crear rol"; save.textContent = "Crear rol"; cancel.hidden = true; updateScope(); };
  const render = () => { roles.innerHTML = ""; if (!state.roles.length) { roles.textContent = "Aún no hay roles."; roles.classList.add("empty"); return; } roles.classList.remove("empty"); state.roles.forEach((role) => { const item = document.createElement("article"); item.className = "role"; const info = document.createElement("div"); const title = document.createElement("strong"); title.textContent = role.label; const meta = document.createElement("div"); meta.className = "muted"; meta.textContent = `${role.id} · ${role.scope === "management" ? "Gestión" : "Externo"} · ${role.permissions.length ? role.permissions.join(", ") : "sin permisos de núcleo"}`; info.append(title, meta); const actions = document.createElement("div"); actions.className = "resource-actions"; const edit = document.createElement("button"); edit.className = "secondary"; edit.textContent = "Editar"; edit.onclick = () => { state.editing = role; id.value = role.id; id.disabled = true; label.value = role.label; scope.value = role.scope; form.querySelectorAll("input[type=checkbox]").forEach((input) => input.checked = role.permissions.includes(input.value)); $("#form-title").textContent = `Editar ${role.label}`; save.textContent = "Guardar cambios"; cancel.hidden = false; updateScope(); window.scrollTo({ top: 0, behavior: "smooth" }); }; actions.append(edit); if (!role.system) { const remove = document.createElement("button"); remove.className = "danger"; remove.textContent = "Eliminar"; remove.onclick = async () => { if (!confirm(`Eliminar el rol ${role.label}?`)) return; try { await api(`/api/admin/roles/${encodeURIComponent(role.id)}`, "DELETE"); await load(); } catch (error) { notice.textContent = error.message; } }; actions.append(remove); } item.append(info, actions); roles.append(item); }); };
  const load = async () => { try { state.roles = (await api("/api/admin/roles")).roles; render(); } catch (error) { roles.textContent = error.message; } };
  scope.onchange = updateScope; cancel.onclick = reset;
  form.onsubmit = async (event) => { event.preventDefault(); notice.textContent = ""; const body = { id: id.value.trim(), label: label.value.trim(), scope: scope.value, permissions: selected() }; try { if (state.editing) await api(`/api/admin/roles/${encodeURIComponent(state.editing.id)}`, "PUT", body); else await api("/api/admin/roles", "POST", body); notice.textContent = "Rol guardado."; reset(); await load(); } catch (error) { notice.textContent = error.message; } };
  updateScope(); load();
})();
